### ISSUE TITLE
KeySaver Not Activating

### ISSUE THREAD

**Issue by gobiyoga** [jwrpalmer99/LogitechVentMonitor#3]
Hello,

I'm trying to make the keysaver work correctly. 

It's currently set to 10 seconds and I wait even a minute and it still doesn't work.

When I first open the application the keysaver seems to work, but after I press a key it will never work again.

Also when I open as admin, I get this error but when I click continue, it seems fine:

---

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

*************\* Exception Text **************
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Average(IEnumerable`1 source)
   at WhoIsSpeaking.HardwareMonitor.getGPUtemp() in C:\Users\web\OneDrive\Documents\LogitechVentMonitor-master\WhoIsSpeaking\WhoIsSpeaking\HardwareMonitor.cs:line 90
   at WhoIsSpeaking.Form1.getTemperatures() in C:\Users\web\OneDrive\Documents\LogitechVentMonitor-master\WhoIsSpeaking\WhoIsSpeaking\Form1.cs:line 1220
   at WhoIsSpeaking.Form1.Form1_Load(Object sender, EventArgs e) in C:\Users\web\OneDrive\Documents\LogitechVentMonitor-master\WhoIsSpeaking\WhoIsSpeaking\Form1.cs:line 1192
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

*************\* Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1063.1 built by: NETFXREL3STAGE
##     CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll

WhoIsSpeaking
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///C:/Users/web/OneDrive/Documents/LogitechVentMonitor-master/WhoIsSpeaking/WhoIsSpeaking/bin/Release/WhoIsSpeaking.exe

System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll

System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

Ini.Net
    Assembly Version: 1.0.5531.18665
    Win32 Version: 1.0.0.0
##     CodeBase: file:///C:/Users/web/OneDrive/Documents/LogitechVentMonitor-master/WhoIsSpeaking/WhoIsSpeaking/bin/Release/Ini.Net.DLL

ColorManagment
    Assembly Version: 3.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///C:/Users/web/OneDrive/Documents/LogitechVentMonitor-master/WhoIsSpeaking/WhoIsSpeaking/bin/Release/ColorManagment.DLL

OpenHardwareMonitorLib
    Assembly Version: 0.7.1.0
    Win32 Version: 0.7.1.0
##     CodeBase: file:///C:/Users/web/OneDrive/Documents/LogitechVentMonitor-master/WhoIsSpeaking/WhoIsSpeaking/bin/Release/OpenHardwareMonitorLib.DLL

System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll

PInvokeDelegateFactoryInternalAssembly
    Assembly Version: 0.0.0.0
    Win32 Version: 0.7.1.0
##     CodeBase: file:///C:/Users/web/OneDrive/Documents/LogitechVentMonitor-master/WhoIsSpeaking/WhoIsSpeaking/bin/Release/OpenHardwareMonitorLib.dll

*************\* JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by jwrpalmer99** [comment]
OK I guess the error message is due to the hwmonitor lib not being able to enumerate your graphics cards, I will place an error handler round that

I will update to the latest version of the Logitech SDK in the hope that it will fix your other problem

**Comment by gobiyoga** [comment]
Alright. I will try it out when I get back to my computer.
Thank you so much for this!

On Tue, Jan 05, 2016 at 4:39 AM, jwrpalmer99 < notifications@github.com [notifications@github.com] > wrote:
OK I guess the error message is due to the hwmonitor lib not being able to
enumerate your graphics cards, I will place an error handler round that

I will update to the latest version of the Logitech SDK in the hope that it will
fix your other problem

—
Reply to this email directly or view it on GitHub
[https://github.com/jwrpalmer99/LogitechVentMonitor/issues/3#issuecomment-168948626] .[https://github.com/notifications/beacon/AFVmsHXw4yFPmw8ZACr4JDuGjZtdv2BZks5pW4aWgaJpZM4G9G-I.gif]
